### PR TITLE
4-space indentation

### PR DESCRIPTION
**Pull request by adidahiya**

### CODE REVIEW

**Comment by adidahiya** [comment]
@rcchen

**Comment by tomshen** [comment]
The issue with changing this now is that every Highline-generated app currently uses 2 spaces, so they'd all have to override this (or change all their Less files) if they use this config.

**Comment by rcchen** [comment]
@tomshen save this one for `2.0.0` and in the meantime just override? I think most older projects are on four spaces.

**Comment by adidahiya** [comment]
we could just 2.0.0 right now

**Comment by rcchen** [comment]
Not opposed to that either @adidahiya 😛

**Comment by tomshen** [comment]
That sounds good to me. We need to fix the example CSS though.

**Comment by adidahiya** [comment]
yup i'll go ahead and fix the build

**Comment by giladgray** [comment]
Why?? I'm strongly against this change. 2 spaces is plenty for CSS, especially with preprocessors' propensity for nesting.

**Comment by rcchen** [comment]
@giladgray shouldn't indentation be somewhat consistent across a codebase? Basically flagging how the standard before was 4-space throughout and with the current stylelint config it's 4-space for JS/TS and 2-space for CSS

**Comment by giladgray** [comment]
I quite prefer the distinction there (4 spaces for "real code") and with a simple EditorConfig file my editor will seamlessly transition as necessary. 

This feels like an incredibly painful break for every dev and every CSS file. Pain far outsizes its benefit.

**Comment by rcchen** [comment]
Re: your second point, hasn't it only been several weeks since stylelint-config has been bundled, and thus not that many repos have been generated with this config yet? A cursory search for `stylelint-config` internally mostly shows test repos. Also this is just conjecture but I think the vast majority of our codebases are still on 4-space everywhere, which means lots of pain to even adopt stylelint-config in the first place.

**Comment by giladgray** [comment]
In my experience, 2-space indentation is the industry standard for CSS. I only accept 4 spaces for TS because it looks more like Java than like CSS (2 spaces all the way in personal projects).

http://www.w3schools.com/html/html5_syntax.asp (scroll down to Style Sheets, see 3rd bullet)

**Comment by rcchen** [comment]
I'm guessing this isn't happening, @adidahiya want to close this one out?

**Comment by adidahiya** [comment]
talked with @giladgray offline a few weeks ago; I'd still like to go for 4-space indentation in Less and Sass. I'll update this PR

**Comment by giladgray** [comment]
@rcchen tell me about these 2-space benefits you speak of. I have no plans to update any of my codebases to use 4 spaces, it's just too big of a break for little clear benefit.

**Comment by rcchen** [comment]
@giladgray in scenarios where my window is not very large horizontally (split screen) I can see a little more code without scrolling 😛 however, I'm not happy about my editor (Atom) having difficulty figuring out whether it ought to tab 2-space or 4-space in a project that has both.

**Comment by tomshen** [comment]
@rcchen you should be able to set language-specific tab sizing in Atom: http://blog.atom.io/2014/10/31/language-scoped-config.html

**Comment by adidahiya** [comment]
I think using 4 spaces further discourages deep nesting in Less/Sass. Compared to TypeScript, you should have no problem fitting Less/Sass code into a narrow editor window.

**Pull request merged**
