### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by tomshen**

### CODE REVIEW

**Comment by tomshen** [comment]
@adidahiya

**Comment by adidahiya** [comment]
@tomshen if we do this, don't we need to make stylelint-config-standard a peer dependency as well? otherwise, users will get no indication that they need to install that dependency at `npm install` time.

**Comment by tomshen** [comment]
That's true. We could also keep it as a dependency, but then we should fix the README to tell users not to install stylelint-config-standard (since extending this will pull in the version of stylelint-config-standard this depends on, rather than the one the user has installed). Which would you prefer?

**Comment by giladgray** [comment]
why do this in the first place? seems like it's more hassle than making it a regular dependency.

i would also argue that, given the way stylelint-config-standard is used, it _should be_ a regular dependency: `.stylelintrc.json` expects it to exist to be extended, and probably wants a specific version too.

**Comment by tomshen** [comment]
Here's the changes I made:

- stylelint is now a peer dependency
- stylelint-config-standard is now a normal dependency
- Updated instructions in README to reflect changes

Does that seem reasonable?

**Pull request merged**
